export interface ReferralDoctor {
    id: number;
    doctor_name: string;
    clinic_name?: string;
    mobile_number: string;
    speciality_type?: string;
    department_id?: number;
    address?: string;
    medical_council_membership_number?: string;
    council?: string;
    pan_card_number?: string;
    aadhar_card_number?: string;
    bank_name?: string;
    bank_branch?: string;
    bank_address?: string;
    bank_account_number?: string;
    bank_ifsc_code?: string;
    referral_pay?: number;
    geo_latitude?: string;
    geo_longitude?: string;
    geo_accuracy?: string;
    photo_upload_path?: string;
    pan_upload_path?: string;
    aadhar_upload_path?: string;
    clinic_photo_path?: string;
    kyc_upload_path?: string;
    created_at?: string;
    updated_at?: string;
}
